os: osx
language: swift
# macOS images: https://docs.travis-ci.com/user/reference/osx#macos-version
osx_image: xcode11.2

before_install:
  - brew tap bazelbuild/tap
  - brew tap-pin bazelbuild/tap
  - brew install bazel

script:
  - bazel version
  - bazel build //:tulsi
  - bazel test //src/TulsiGeneratorTests --test_output=errors --nocheck_visibility
  - bazel test //src/TulsiGeneratorIntegrationTests --test_output=errors --nocheck_visibility
